var choo = require('choo')
var persist = require('choo-persist')
var devtools = require('choo-devtools')

var store = require('./store')
var summary = require('./views/summary')
var transactions = require('./views/transactions')

var app = choo()
app.use(devtools())
app.use(persist())
app.use(store)
app.route('/', transactions)
app.route('#/summary', summary)
app.route('#/transactions', transactions)
app.mount('body')
